version: '3'
services:
  apache:
    container_name: srv-drupal-apache
    image:  jorarmarfin/drupal:tmp
    volumes:
      - ./apache/www:/var/www
      - ./apache/backup:/backup
    ports:
      - 9005:80
    networks:
      - net_drupal
  db:
    container_name: srv-drupal-mysql
    image:  mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/backup:/backup
    networks:
      - net_drupal
networks:
  net_drupal: